references:
language: objective-c
osx_image: xcode10.2
#xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone x

cache: cocoapods
podfile: Example/Podfile
before_install:
 - sudo gem install activesupport -v 4.2.6
 - rvm install 2.3.1
 - rvm use 2.3.1
 - sudo gem install cocoapods
 - gem install xcpretty -N
 #- brew install swiftlint || true
 
script:
 - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SimpleQR.xcworkspace -scheme SimpleQR-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
 #- swiftlint
 - pod lib lint
